PYTORCH_FALLBACK_OPS = {
    "add": False,
    "group norm": False,
    "layer norm": False,
    "gelu": False,
    "linear": False,
    "conv": False,
    "slice": False,
    "concat": False,
    "repeat_interleave": False,
    "bcast add": False,
    "bmm": False,
    "pad": False,
    "full": False,
    "mul": False,
    "split": False,
    "permute": True,
    "reshape": False,
    "softmax": False,
    "transpose": False,
    "silu": False,
}
