name: "(T3K) T3000 perplexity tests"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 6" # This cron schedule runs the workflow every saturday at 12pm

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    with:
      arch: '["wormhole_b0"]'
    secrets: inherit
  t3000-model-perf-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/t3000-perplexity-tests-impl.yaml
